### ISSUE TITLE
pyodbc runtime is not supported

### ISSUE THREAD

**Issue by gangularamya** [Azure-App-Service/python#14] opened 2018-11-28 05:29 UTC
Most of the webapps in Python would try to connect external database using pyodbc
Looks like we are Unable to use pyodbc as Python Image doesn't have unixodbc installed in App Container
https://github.com/mkleehammer/pyodbc/wiki/Install

I think we might need to add below commands as mentioned in above link..
```
RUN apt-get install g++ unixodbc-dev
```

![image](https://user-images.githubusercontent.com/13338127/49130987-f2abd400-f29b-11e8-87a3-806f7ab09c31.png)

**Comment by JennyLawrance** [comment] 2018-12-08 01:54
Ack, taking a look.

**Comment by martincabello** [comment] 2019-01-27 16:40
Any updates on this? I have been trying and trying to deploy my flask app on azure app service, but this is major step on the way. Everything works if I leave out the dependency on pyodbc

**Comment by kfolkes** [comment] 2019-02-01 19:46
I would like an estimated update on this as well.

**Comment by JennyLawrance** [comment] 2019-02-01 19:54
Estimated release time, in the next 2-3 weeks.

**Comment by dsalamancaMS** [comment] 2019-02-20 15:29
Running into same issue, Im not able to connect to my Azure SQL database due to the lack of unixodbc.

**Comment by AcerbragTI** [comment] 2019-02-21 15:07
Any news?...

**Comment by clauney** [comment] 2019-02-21 23:44
Same issue here. @JennyLawrance - any update?

**Comment by martincabello** [comment] 2019-02-28 18:29
Hey! Any news??

**Comment by JennyLawrance** [comment] 2019-02-28 18:30
Yes, can you try now? All our scale units are upgraded, let me know if you still run into issues.

**Comment by martincabello** [comment] 2019-02-28 18:33
I m on it. Will update asap.

**Comment by chriswue** [comment] 2019-05-09 07:57
I can confirm that this works for me. I have just deployed a working python flask app on Linux based app services using pyodbc to connect to an Azure hosted MS SQL database, connecting like this:

    pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)

**Comment by JennyLawrance** [comment] 2019-05-09 17:10
Thanks for the confirmation @martincabello  @chriswue 
Closing the issue.

**Comment by JennyLawrance** [comment] 2019-05-09 17:11
Thanks @gangularamya for reporting this and help make the product better.

**Closed by JennyLawrance** 2019-05-09 17:10 UTC

**Comment by thetestgame** [comment] 2020-02-06 17:17
This issue seems to have come back in a new form. You can not install pyodbc in the default container due to missing dependencies.

**Comment by jaceaser** [comment] 2020-02-13 23:29
Yes, I am having the same issue setting up a new appservice.

**Comment by Relent97** [comment] 2020-05-02 21:59
I am also having the same issue

**Comment by Relent97** [comment] 2020-05-02 22:08
> I m on it. Will update asap.
> EDIT:
> THANK YOU!
> It seems to be working. Can someone else confirm?

Hi @martincabello please can you share how you deployed the app, was it through docker or azure cli.

A github link would be tremendously appreciated please

**Comment by martincabello** [comment] 2020-05-02 23:12
Hey. I cant really recall by now. It was a school project. I think it was through Azure Web UI for webapps and then we used the UI again to hook it up for auto deploy from our repo on github.

**Comment by mitchellpalmer** [comment] 2020-11-02 08:12
Hi there. I am having a similar problem to this which I detailed in [this SO question](https://stackoverflow.com/questions/64640016/how-to-access-odbc-driver-on-azure-app-service). Does anyone have any insights?
